spring:
  application:
    name: api-gateway-ipl
  cloud:
    gateway:
      routes:
        - id: insert-match-data
          uri: http://localhost:8085
          predicates:
            - Path=/api/matches
        - id: get-matches-by-player
          uri: http://localhost:8085
          predicates:
            - Path=/api/matches/player/match/{playerName}
        - id: get-cumulative-score
          uri: http://localhost:8085
          predicates:
            - Path=/api/matches/score
        - id: get-scores-by-date
          uri: http://localhost:8085
          predicates:
            - Path=/api/matches/match/date
        - id: get-top-batsmen
          uri: http://localhost:8085
          predicates:
            - Path=/api/matches/top-batsmen
        - id: get-wicket-count-by-bowler
          uri: http://localhost:8085
          predicates:
            - Path=/api/json-upload/player/wickets

server:
  port: 9004 # API Gateway will run on port 9004
