apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipl-assignment1-deployment
  labels:
    app: ipl-assignment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipl-assignment1
  template:
    metadata:
      labels:
        app: ipl-assignment1
    spec:
      containers:
        - name: ipl-assignment1
          image: ipl-assignment1:0.1
          env:
            - name: KAFKA_HOST
              value: "host.docker.internal:9094"
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: MYSQL_URL
              value: "jdbc:mysql://host.docker.internal:1000/ipl_match"
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "512Mi"  # Increased from 128Mi
              cpu: "500m"      # Increased from 250m
            limits:
              memory: "1Gi"   # Increased from 256Mi
              cpu: "1"        # Increased from 500m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ipl-assignment1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ipl-assignment1-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: ipl-assignment1-service
spec:
  selector:
    app: ipl-assignment1
  type: NodePort
  ports:
    - port: 80
      targetPort: 8085
      nodePort: 30005
